<header class="row">
    <div class="col-xs-4 col-sm-2 col-md-2 ">
        <a id="logo" href="<?php echo Core_Library_Account::GetInstance()->GetCurrentProject()->GetURL(); ?>">
            <img src="<?php echo Core_Library_Options::get( 'voozanoo.baseurl' ) ?>images/logo.svg" alt="logo" />
        </a>
    </div>

    <div class="col-xs-8 col-sm-4 col-md-6 title hidden-sm hidden-md hidden-lg">
        <h1 class="hidden-xs hidden-sm"><?php echo $this->sPageTitle ?></h1>
        <h2 class="hidden-xs hidden-sm">Application de collecte et de pilotage budgétaire</h2>
        <h1 class="hidden-md hidden-lg"><?php echo $this->sPageTitle ?></h1>
        <h2 class="hidden-md hidden-lg">Application de collecte et de pilotage budgétaire</h2>
    </div>

    <div class="col-xs-10 col-sm-4 col-md-3 hidden-xs">

        <?php if(file_exists( 'images/logo_partn1.png' ) ): ?>
        <div class="col-xs-4 col-sm-6">
            <a class="logo-partn" href="http://ined.fr" target="_blank">
                <img src="<?php echo Core_Library_Options::get( 'voozanoo.baseurl' ) ?>images/logo_partn1.png" alt="logo" />
            </a>
        </div>
        <?php endif ?>

        <?php if(file_exists( 'images/logo_partn2.png' ) ): ?>
        <div class="col-xs-4 col-sm-6">
            <a class="logo-partn" href="http://ined.fr" target="_blank">
                <img src="<?php echo Core_Library_Options::get( 'voozanoo.baseurl' ) ?>images/logo_partn2.png" alt="logo" />
            </a>
        </div>
        <?php endif ?>

    </div>

    <div class="col-sm-4 col-md-6 title hidden-xs">
        <h1 class="hidden-xs hidden-sm"><?php echo $this->sPageTitle ?></h1>
        <h2 class="hidden-xs hidden-sm">Application de collecte et de pilotage budgétaire</h2>
        <h1 class="hidden-md hidden-lg"><?php echo $this->sPageTitle ?></h1>
        <h2 class="hidden-md hidden-lg">Application de collecte et de pilotage budgétaire</h2>
    </div>


    <div class="col-sm-2 col-xs-2 hidden-lg hidden-md col-xs-offset-10">
        <a class="btn btn-sm btn-danger pull-right" href="<?=Core_Library_Account::GetInstance()->GetCurrentProject()->GetURL() ?>auth/index/disconnect">D&eacute;connexion</a>
    </div>

    <?php echo $this->partial( 'menu.phtml' ); ?>


</header>