<footer>
    <div class="col-xs-12 visible-xs">

        <?php if(file_exists( 'images/logo_partn1.png' ) ): ?>
            <div class="col-xs-5">
                <a class="logo-partn" href="http://ined.fr" target="_blank">
                    <img src="<?php echo Core_Library_Options::get( 'voozanoo.baseurl' ) ?>images/logo_partn1.png" alt="logo" />
                </a>
            </div>
        <?php endif ?>

        <?php if(file_exists( 'images/logo_partn2.png' ) ): ?>
            <div class="col-xs-5 col-xs-offset-2">
                <a class="logo-partn" href="http://ined.fr" target="_blank">
                    <img src="<?php echo Core_Library_Options::get( 'voozanoo.baseurl' ) ?>images/logo_partn2.png" alt="logo" />
                </a>
            </div>
        <?php endif ?>

    </div>

    <div class="hidden-xs">
        <a class="col-xs-6" href="http://www.ined.fr" target="_blank">Copyright Ined 2014-2017</a>
        <a class="col-xs-6 text-right" href="https://portal.voozanoo.net" target="_blank">Basé sur la plateforme Voozanoo</a>
    </div>
    <div class="visible-xs">
        <a class="col-xs-12" href="http://www.ined.fr" target="_blank">Copyright Ined 2014-2017</a>
        <a class="col-xs-12" href="https://portal.voozanoo.net" target="_blank">Basé sur la plateforme Voozanoo</a>
    </div>
</footer>