<footer>
    <div class="container hidden-xs">
        <a class="col-xs-6" href="http://www.ined.fr" target="_blank">Copyright Ined 2014</a>
        <a class="col-xs-6 text-right" href="https://portal.voozanoo.net" target="_blank">Basé sur la plateforme Voozanoo</a>
    </div>
    <div class="container visible-xs">
        <a class="col-xs-12" href="http://www.ined.fr" target="_blank" style="margin-top: 15px">Copyright Ined 2014</a>
        <a class="col-xs-12" href="https://portal.voozanoo.net" target="_blank" style="margin-top: 15px">Basé sur la plateforme Voozanoo</a>
    </div>
</footer>