<?php
//Alias pour alléger l'HTML ci-dessous
$sProjectUrl = Core_Library_Account::GetInstance()->GetCurrentProject()->GetURL();

//Si l'utilisateur à le role "1" il est considéré comme admin, sinon non
$bIsAdmin = Core_Library_Account::GetInstance()->GetCurrentUser()->HasRole( 1 ) ? true : false;
?>
<nav class="navbar navbar-default col-xs-12" role="navigation">

    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand text-right visible-xs" href="#">Menu <span class="glyphicon glyphicon-arrow-right"></span></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li class="">
                <a class="" href="#" onclick="Y.Voozanoo.backToHome();">
                    <span class="glyphicon glyphicon-home"></span> Accueil
                </a>
            </li>

            <li class="">
                <a class="" onclick="Y.Voozanoo.oMainFrame.goToFrame( 'form/frame/get/id/50')" href="#">
                    <span class="fa fa-table"></span> Tableur
                </a>
            </li>


            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <span class="glyphicon glyphicon-list"></span> Formation
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a onclick="Y.Voozanoo.oMainFrame.goToFrame( 'form/frame/get/id/20' )" href="#">Formulaire Raphaël [20]</a></li>
                    <li><a onclick="Y.Voozanoo.oMainFrame.goToFrame( 'form/frame/get/id/24' )" href="#">Listing Raphael [24]</a></li>
                    <li><a onclick="Y.Voozanoo.oMainFrame.goToFrame( 'form/frame/get/id/46' )" href="#">CSS Raphael [46]</a></li>
                    <li class="divider"></li>
                    <li><a onclick="Y.Voozanoo.oMainFrame.goToFrame( 'form/frame/get/id/21' )" href="#">Formulaire Kamel [21]</a></li>
                    <li><a onclick="Y.Voozanoo.oMainFrame.goToFrame( 'form/frame/get/id/25' )" href="#">Listing Kamel [25]</a></li>
                    <li><a onclick="Y.Voozanoo.oMainFrame.goToFrame( 'form/frame/get/id/48' )" href="#">CSS Kamel [48]</a></li>
                    <li class="divider"></li>
                    <li><a onclick="Y.Voozanoo.oMainFrame.goToFrame( 'form/frame/get/id/22' )" href="#">Formulaire Arnaud [22]</a></li>
                    <li><a onclick="Y.Voozanoo.oMainFrame.goToFrame( 'form/frame/get/id/26' )" href="#">Listing Arnaud [26]</a></li>
                    <li><a onclick="Y.Voozanoo.oMainFrame.goToFrame( 'form/frame/get/id/47' )" href="#">CSS Arnaud [47]</a></li>
                </ul>
            </li>
            <li class="">
                <a class="" onclick="Y.Voozanoo.oMainFrame.goToFrame( 'form/frame/get/id/21' )" href="#">
                    <span class="glyphicon glyphicon-inbox"></span> Lien 1
                </a>
            </li>

            <li class="">
                <a class="" onclick="Y.Voozanoo.oMainFrame.goToFrame( 'form/frame/get/id/47' )" href="#">
                    <span class="glyphicon glyphicon-book"></span> Lien 2
                </a>
            </li>
        </ul>
        <p style="margin-bottom: -40px"></p>
        <ul class="nav navbar-nav navbar-right hidden-xs hidden-sm">
            <li class="">
                <a class="" href="<?=Core_Library_Account::GetInstance()->GetCurrentProject()->GetURL() ?>auth/index/disconnect">
                    <span class="glyphicon glyphicon-log-out"></span> D&eacute;connexion
                </a>
            </li>
        </ul>
        <?php if ($bIsAdmin): ?>
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <span class="glyphicon glyphicon-wrench"></span> Admin.
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a onclick="Y.Voozanoo.oMainFrame.goToFrame( 'resource/list/index' )" href="#">Ressources</a></li>
                    <li><a onclick="Y.Voozanoo.oMainFrame.goToFrame( 'dico/list/index' )" href="#">Dictionnaires</a></li>
                    <li class="divider"></li>
                    <li><a onclick="Y.Voozanoo.oMainFrame.goToFrame( 'project/group/getgroups' )" href="#">Groupes</a></li>
                    <li><a onclick="Y.Voozanoo.oMainFrame.goToFrame( 'project/role/getroles' )" href="#">Rôles</a></li>
                    <li><a onclick="Y.Voozanoo.oMainFrame.goToFrame( 'project/user/getusers' )" href="#">Utilisateurs</a></li>
                    <li></li> <!-- évite que le dernier element de la liste soit en float right dans le menu déroulant -->
                </ul>
            </li>
        </ul>
        <?php endif ?>
    </div>
</nav>