/* Inclusion des fonts */
@font-face {
    font-family: 'open_sansregular';
    src: url('<?php echo $this->baseUrl(); ?>/fonts/opensans-regular-webfont.eot');
    src: url('<?php echo $this->baseUrl(); ?>/fonts/opensans-regular-webfont.eot?#iefix') format('embedded-opentype'),
    url('<?php echo $this->baseUrl(); ?>/fonts/opensans-regular-webfont.svg#open_sansregular') format('svg'),
    url('<?php echo $this->baseUrl(); ?>/fonts/opensans-regular-webfont.woff') format('woff'),
    url('<?php echo $this->baseUrl(); ?>/fonts/opensans-regular-webfont.woff2') format('woff2'),
    url('<?php echo $this->baseUrl(); ?>/fonts/opensans-regular-webfont.ttf') format('truetype');

    font-weight: normal;
    font-style: normal;

}

@font-face {
    font-family: 'open_sansbold';
    src: url('<?php echo $this->baseUrl(); ?>/fonts/opensans-bold-webfont.eot');
    src: url('<?php echo $this->baseUrl(); ?>/fonts/opensans-bold-webfont.eot?#iefix') format('embedded-opentype'),
    url('<?php echo $this->baseUrl(); ?>/fonts/opensans-bold-webfont.woff2') format('woff2'),
    url('<?php echo $this->baseUrl(); ?>/fonts/opensans-bold-webfont.woff') format('woff'),
    url('<?php echo $this->baseUrl(); ?>/fonts/opensans-bold-webfont.ttf') format('truetype'),
    url('<?php echo $this->baseUrl(); ?>/fonts/opensans-bold-webfont.svg#open_sansbold') format('svg');
    font-weight: normal;
    font-style: normal;

}

/* Style spécifique pour mobile */
@media (max-width: 767px) {
    .pull-bottom {
        margin-top: 65px;
    }

    .navbar-collapse {
        max-height: none;
    }

    .navbar-nav {
        width: 100%;
        display: inline;
    }

    .navbar-nav > li:not(.no-list) {
        display: block !important;
    }

    .navbar-nav > li > a {
        width: 100%;
        display: block !important;
    }
}

body {
    background: none repeat scroll 0 0 #f5f5f5;
    color: #4e5762;
    font-family: "open_sansregular";
    font-weight: 400;
    position: relative;
    padding-top: 0
}

h1, h2, h3, h4, h5, h6 {
    color: #212d3a;
    font-family: "open_sansbold";
    line-height: 1.422em;
    padding-bottom: 0.336em;
    padding-top: 0.336em;
    text-rendering: optimizelegibility
}

#page .h1-like, #page .h2-like, #page .h3-like, #page .h4-like, #page .h5-like {
    font-weight: normal;
    font-family: "open_sansbold" !important;
}

div.statictext, div.vzn-label, div.field, .radio-inline, .checkbox-inline, label.control-label {
    font-family: "open_sansregular"
}

#page {
    /*border-radius*/
    -moz-border-radius: 0;
    -webkit-border-radius: 0;
    border-radius: 0;
    padding: 20px
}

#logo, .logo-partn {
    display: inline-block;
    max-width: 100%;
    width: 100%
}

#logo img, .logo-partn img {
    width: 100%
}

.logo-partn{
    margin-top: 18px;
}

header.row {
    position: relative;
    margin-left: -20px;
    margin-right: -20px
}

.title{
    padding: 0 5px;
}

.title h2{
    margin-top: 0;
}

footer {
    border-top: 1px solid #d3d3d3;
}

footer > div > a {
    margin-top: 15px;
}

/* Style spécifique pour la navabr INED */

.navbar-default {
    margin-top: 10px;
    background: linear-gradient(to bottom, #1b1c1e 0%, #2c3846 100%) repeat scroll 0 0 rgba(0, 0, 0, 0);
    border: none;
    -moz-border-radius: 0;
    -webkit-border-radius: 0;
    border-radius: 0
}

.navbar-default ul.navbar-nav > li {
    border-collapse: collapse;
    border-left: 1px solid #394251;
    border-right: 1px solid #010000;
    display: table-cell;
    min-height: 55px;
    padding-bottom: 0;
    -moz-transition: -moz-background 0.5s ease 0s;
    -o-transition: -o-background 0.5s ease 0s;
    -webkit-transition: -webkit-background 0.5s ease 0s;
    transition: background 0.5s ease 0s;
    vertical-align: top
}

.navbar-default ul.navbar-nav > li > a {
    border-bottom: 5px solid #fff;
    color: #fff;
    display: table-cell;
    vertical-align: middle;
    font-family: open_sansbold;
    font-size: 1em;
    height: 51px;
    line-height: 1em;
    padding: 10px;
    text-align: center;
    text-transform: uppercase;
    -moz-transition: border-bottom-width 0.2s ease 0s, -moz-background 0.2s ease 0s;
    -o-transition: border-bottom-width 0.2s ease 0s, -o-background 0.2s ease 0s;
    -webkit-transition: border-bottom-width 0.2s ease 0s, -webkit-background 0.2s ease 0s;
    transition: border-bottom-width 0.2s ease 0s, background 0.2s ease 0s;
    width: 100%
}

.navbar-default .navbar-nav > li > a:hover, .navbar-default .navbar-nav > li > a:focus {
    color: #FFF
}

.navbar-default .navbar-nav > .open > a, .navbar-default .navbar-nav > .open > a:hover, .navbar-default .navbar-nav > .open > a:focus {
    color: #fff;
    background: transparent
}

.navbar-default ul.navbar-nav > li:nth-child(1) > a {
    border-bottom: 5px solid #e9362f
}

.navbar-default ul.navbar-nav > li:nth-child(2) > a {
    border-bottom: 5px solid #f8aa24
}

.navbar-default ul.navbar-nav > li:nth-child(3) > a {
    border-bottom: 5px solid #7e69b4
}

.navbar-default ul.navbar-nav > li:nth-child(4) > a {
    border-bottom: 5px solid #b39482
}

.navbar-default ul.navbar-nav > li:nth-child(5) > a {
    border-bottom: 5px solid #1d875f
}

.navbar-default ul.navbar-nav > li:nth-child(6) > a {
    border-bottom: 5px solid #1cbdc7
}

.navbar-default ul.navbar-nav > li:nth-child(7) > a {
    border-bottom: 5px solid #212d3a
}

.navbar-default ul.navbar-nav > li:nth-child(8) > a {
    border-bottom: 5px solid #ec7724
}

.navbar-default ul.navbar-nav > li:nth-child(1) > a:hover, .navbar-default ul.navbar-nav > li:nth-child(1) > a:focus, .navbar-default ul.navbar-nav > li:nth-child(1) > a:active, .navbar-default ul.navbar-nav > li:nth-child(1) .dropdown-menu {
    background: none repeat scroll 0 0 #e9362f !important
}

.navbar-default ul.navbar-nav > li:nth-child(2) > a:hover, .navbar-default ul.navbar-nav > li:nth-child(2) > a:focus, .navbar-default ul.navbar-nav > li:nth-child(2) > a:active, .navbar-default ul.navbar-nav > li:nth-child(2) .dropdown-menu {
    background: none repeat scroll 0 0 #f8aa24 !important
}

.navbar-default ul.navbar-nav > li:nth-child(3) > a:hover, .navbar-default ul.navbar-nav > li:nth-child(3) > a:focus, .navbar-default ul.navbar-nav > li:nth-child(3) > a:active, .navbar-default ul.navbar-nav > li:nth-child(3) .dropdown-menu {
    background: none repeat scroll 0 0 #7e69b4 !important
}

.navbar-default ul.navbar-nav > li:nth-child(4) > a:hover, .navbar-default ul.navbar-nav > li:nth-child(4) > a:focus, .navbar-default ul.navbar-nav > li:nth-child(4) > a:active, .navbar-default ul.navbar-nav > li:nth-child(4) .dropdown-menu {
    background: none repeat scroll 0 0 #b39482 !important
}

.navbar-default ul.navbar-nav > li:nth-child(5) > a:hover, .navbar-default ul.navbar-nav > li:nth-child(5) > a:focus, .navbar-default ul.navbar-nav > li:nth-child(5) > a:active, .navbar-default ul.navbar-nav > li:nth-child(5) .dropdown-menu {
    background: none repeat scroll 0 0 #1d875f !important
}

.navbar-default ul.navbar-nav > li:nth-child(6) > a:hover, .navbar-default ul.navbar-nav > li:nth-child(6) > a:focus, .navbar-default ul.navbar-nav > li:nth-child(6) > a:active, .navbar-default ul.navbar-nav > li:nth-child(6) .dropdown-menu {
    background: none repeat scroll 0 0 #1cbdc7 !important
}

.navbar-default ul.navbar-nav > li:nth-child(7) > a:hover, .navbar-default ul.navbar-nav > li:nth-child(7) > a:focus, .navbar-default ul.navbar-nav > li:nth-child(7) > a:active, .navbar-default ul.navbar-nav > li:nth-child(7) .dropdown-menu {
    background: none repeat scroll 0 0 #212d3a !important
}

.navbar-default ul.navbar-nav > li:nth-child(8) > a:hover, .navbar-default ul.navbar-nav > li:nth-child(8) > a:focus, .navbar-default ul.navbar-nav > li:nth-child(8) > a:active, .navbar-default ul.navbar-nav > li:nth-child(8) > .dropdown-menu {
    background: none repeat scroll 0 0 #ec7724 !important
}

.navbar-default .navbar-nav > li.dropdown.open > a.dropdown-toggle {
    border-bottom-width: 8px !important
}

.navbar-default .navbar-nav > li > .dropdown-menu {
    -moz-border-radius: 0;
    -webkit-border-radius: 0;
    border-radius: 0;
    border: 0;
    -moz-box-shadow: none;
    -webkit-box-shadow: none;
    box-shadow: none;
    font: 14px OpenSans, Helvetica, Geneva, sans-serif;
    color: #FFF
}

.navbar-default .navbar-nav > li > .dropdown-menu > li > a {
    color: #FFF !important
}

.navbar-default .navbar-nav > li:nth-child(1) > .dropdown-menu > li > a:hover {
    background-color: #e55857 !important
}

.navbar-default .navbar-nav > li:nth-child(2) > .dropdown-menu > li > a:hover {
    background-color: #facc7b !important
}

.navbar-default .navbar-nav > li:nth-child(3) > .dropdown-menu > li > a:hover {
    background-color: #aea3d8 !important
}

.navbar-default .navbar-nav > li:nth-child(4) > .dropdown-menu > li > a:hover {
    background-color: #d1beb2 !important
}

.navbar-default .navbar-nav > li:nth-child(5) > .dropdown-menu > li > a:hover {
    background-color: #a2cec0 !important
}

.navbar-default .navbar-nav > li:nth-child(6) > .dropdown-menu > li > a:hover {
    background-color: #78d7da !important
}

.navbar-default .navbar-nav > li:nth-child(7) > .dropdown-menu > li > a:hover {
    background-color: #3a4653 !important
}

.navbar-default .navbar-nav > li:nth-child(8) > .dropdown-menu > li > a:hover {
    background-color: #ffa653 !important
}

.navbar-default ul.navbar-nav a.deco {
    margin-top: 10px;
    padding-bottom: 7px
}

.navbar-default ul.navbar-nav > li.no-list:nth-child(2) > a {
    border: 0
}

.navbar-default ul.navbar-nav > li.no-list > a {
    display: block;
    height: initial;
    width: 100%
}

.navbar-default .navbar-nav.navbar-right:last-child {
    margin-right: 0
}

.navbar-default ul.navbar-nav > li.no-list > a:hover {
    background: #d2322d !important
}

h3, .h3 {
    font-size: 24px !important;
}

.under-title {
    border-bottom: 1px solid #000000;
    display: block;
    width: 100%;
}

